# Generated by Django 3.0.3 on 2020-03-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_song_song_file'),
        ('users', '0002_auto_20200324_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='fav_songs',
            field=models.ManyToManyField(blank=True, related_name='users_fav', to='music.Song'),
        ),
    ]
