# Generated by Django 3.0.3 on 2020-03-10 02:32

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20200310_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_file',
            field=models.FileField(null=True, upload_to=music.models.song_directory_path),
        ),
    ]
